# Generated by Django 5.0.4 on 2024-04-23 07:52

import django.db.models.deletion
import phone_field.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, default=None, help_text='Contact phone number', max_length=31)),
                ('invite_code', models.CharField(default='PBRCFR', verbose_name='Invite code')),
                ('code', models.CharField(default=None, max_length=4, verbose_name='Login Code')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Connected_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата подключения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conntected_user_extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userupdate', verbose_name='Пользователь')),
            ],
        ),
    ]
