# Generated by Django 5.0.4 on 2024-04-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupdate',
            name='invite_code',
            field=models.CharField(default='KTMHIE', verbose_name='Invite code'),
        ),
    ]
