# Generated by Django 5.0.4 on 2024-04-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userupdate_invite_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupdate',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Login Code'),
        ),
        migrations.AlterField(
            model_name='userupdate',
            name='invite_code',
            field=models.CharField(default='BVQ6E4', verbose_name='Invite code'),
        ),
    ]
